services:
  # Our PostgreSQL database
  db:
    # Using the latest PostgreSQL image
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: changemeinprod!
      TZ: Asia/Kolkata
      PGTZ: Asia/Kolkata

  # Database management interface
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080